"""Reports — download per-image and campaign summary PDFs."""

import io
import sys
import zipfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import streamlit as st

from app.components.data_loader import get_db_path, load_pdf_records

st.set_page_config(page_title="Reports", page_icon="📄", layout="wide")

with st.sidebar:
    st.title("GP Screen Analysis")
    st.divider()
    st.info(
        "PDF reports are generated by running:\n\n"
        "`python scripts/batch_report.py`"
    )

db_path = get_db_path()
pdf_df = load_pdf_records(db_path)

st.title("Reports")
st.caption("Download generated PDF reports")
st.divider()

if pdf_df.empty:
    st.warning("No reports found. Run `python scripts/batch_report.py` to generate them.")
    st.stop()

# ---- Campaign summary ----
summary_rows = pdf_df[pdf_df["report_type"] == "summary"]
if not summary_rows.empty:
    st.subheader("Campaign Summary Report")
    for _, row in summary_rows.iterrows():
        pdf_path = Path(row["pdf_path"])
        if pdf_path.exists():
            file_size = pdf_path.stat().st_size
            col_info, col_btn = st.columns([3, 1])
            with col_info:
                st.markdown(f"**{pdf_path.name}**")
                st.caption(f"Size: {file_size // 1024} KB  |  Generated: {row['run_timestamp'][:19]}")
            with col_btn:
                with open(pdf_path, "rb") as f:
                    st.download_button(
                        "Download PDF",
                        data=f.read(),
                        file_name=pdf_path.name,
                        mime="application/pdf",
                        key=f"summary_{row['id']}",
                    )
    st.divider()

# ---- Per-image reports ----
per_image_rows = pdf_df[pdf_df["report_type"] == "per_image"].copy()
if not per_image_rows.empty:
    st.subheader(f"Per-Image Reports ({len(per_image_rows)} files)")

    # Bulk download as zip
    existing = [r for _, r in per_image_rows.iterrows()
                if Path(r["pdf_path"]).exists()]
    if existing:
        zip_buf = io.BytesIO()
        with zipfile.ZipFile(zip_buf, "w", zipfile.ZIP_DEFLATED) as zf:
            for row in existing:
                p = Path(row["pdf_path"])
                zf.write(p, p.name)
        zip_buf.seek(0)
        st.download_button(
            f"Download all {len(existing)} per-image PDFs (ZIP)",
            data=zip_buf,
            file_name="gp_screen_per_image_reports.zip",
            mime="application/zip",
        )
        st.divider()

    for _, row in per_image_rows.iterrows():
        pdf_path = Path(row["pdf_path"])
        if not pdf_path.exists():
            continue
        file_size = pdf_path.stat().st_size
        col_name, col_size, col_ts, col_btn = st.columns([3, 1, 2, 1])
        with col_name:
            st.markdown(f"**{row.get('source_filename', pdf_path.stem)}**")
        with col_size:
            st.caption(f"{file_size // 1024} KB")
        with col_ts:
            st.caption(row["run_timestamp"][:19] if row["run_timestamp"] else "")
        with col_btn:
            with open(pdf_path, "rb") as f:
                st.download_button(
                    "Download",
                    data=f.read(),
                    file_name=pdf_path.name,
                    mime="application/pdf",
                    key=f"per_{row['id']}",
                )
