[theme]
base = "light"
primaryColor = "#1A5988"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#1A1A1A"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
